# Generated by Django 3.2.12 on 2022-03-28 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0009_auto_20220316_1813'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IsGunleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gunleri', models.CharField(max_length=500)),
                ('tarix', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VezifeGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(max_length=500)),
                ('icazeli_gunleri', models.CharField(max_length=500)),
                ('tarix', models.DateTimeField()),
                ('is_gunleri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vezifeler', to='gunler.isgunleri')),
                ('vezife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.vezifeler')),
            ],
        ),
        migrations.CreateModel(
            name='ShobeGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(max_length=500)),
                ('icazeli_gunleri', models.CharField(max_length=500)),
                ('tarix', models.DateTimeField()),
                ('is_gunleri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shobeler', to='gunler.isgunleri')),
                ('shobe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.shobe')),
            ],
        ),
        migrations.CreateModel(
            name='OfisGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(max_length=500)),
                ('icazeli_gunleri', models.CharField(max_length=500)),
                ('tarix', models.DateTimeField()),
                ('is_gunleri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofisler', to='gunler.isgunleri')),
                ('ofis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.ofis')),
            ],
        ),
        migrations.CreateModel(
            name='KomandaGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(max_length=500)),
                ('icazeli_gunleri', models.CharField(max_length=500)),
                ('tarix', models.DateTimeField()),
                ('is_gunleri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komandalar', to='gunler.isgunleri')),
                ('komanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.komanda')),
            ],
        ),
        migrations.CreateModel(
            name='IsciGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(max_length=500)),
                ('icazeli_gunleri', models.CharField(max_length=500)),
                ('tarix', models.DateTimeField()),
                ('is_gunleri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isciler', to='gunler.isgunleri')),
                ('isci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoldingGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(max_length=500)),
                ('icazeli_gunleri', models.CharField(max_length=500)),
                ('tarix', models.DateTimeField()),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.holding')),
                ('is_gunleri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding', to='gunler.isgunleri')),
            ],
        ),
    ]
