# Generated by Django 3.2.12 on 2022-04-17 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gunler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsciGelibGetmeVaxtlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelme_vaxti', models.TimeField()),
                ('getme_vaxti', models.TimeField()),
                ('isci', models.ManyToManyField(related_name='isci_gelib_getme_vaxtlari', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
