# Generated by Django 3.2.12 on 2022-05-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gunler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komandagunler',
            name='is_gunleri',
        ),
        migrations.RemoveField(
            model_name='komandagunler',
            name='komanda',
        ),
        migrations.RemoveField(
            model_name='ofisgunler',
            name='is_gunleri',
        ),
        migrations.RemoveField(
            model_name='ofisgunler',
            name='ofis',
        ),
        migrations.RemoveField(
            model_name='shobegunler',
            name='is_gunleri',
        ),
        migrations.RemoveField(
            model_name='shobegunler',
            name='shobe',
        ),
        migrations.RemoveField(
            model_name='vezifegunler',
            name='is_gunleri',
        ),
        migrations.RemoveField(
            model_name='vezifegunler',
            name='vezife',
        ),
        migrations.RemoveField(
            model_name='iscigunler',
            name='icazeli_gunleri',
        ),
        migrations.RemoveField(
            model_name='iscigunler',
            name='is_gunleri',
        ),
        migrations.AddField(
            model_name='iscigunler',
            name='icaze_gunleri',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='iscigunler',
            name='is_gunleri_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iscigunler',
            name='qeyri_is_gunu_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='iscigunler',
            name='tarix',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='iscigunler',
            name='tetil_gunleri',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='HoldingGunler',
        ),
        migrations.DeleteModel(
            name='IsGunleri',
        ),
        migrations.DeleteModel(
            name='KomandaGunler',
        ),
        migrations.DeleteModel(
            name='OfisGunler',
        ),
        migrations.DeleteModel(
            name='ShobeGunler',
        ),
        migrations.DeleteModel(
            name='VezifeGunler',
        ),
    ]
