# Generated by Django 3.2.12 on 2022-03-30 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20220316_1813'),
        ('gunler', '0002_auto_20220502_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iscigunler',
            old_name='icaze_gunleri',
            new_name='icaze_gunleri_odenisli',
        ),
        migrations.AddField(
            model_name='iscigunler',
            name='icaze_gunleri_odenissiz',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='iscigunler',
            name='tarix',
            field=models.DateField(editable=False),
        ),
        migrations.CreateModel(
            name='VezifeGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gunleri_count', models.PositiveBigIntegerField(default=0)),
                ('qeyri_is_gunu_count', models.PositiveBigIntegerField(default=0)),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('tarix', models.DateField(editable=False)),
                ('vezife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.vezifeler')),
            ],
        ),
        migrations.CreateModel(
            name='ShobeGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gunleri_count', models.PositiveBigIntegerField(default=0)),
                ('qeyri_is_gunu_count', models.PositiveBigIntegerField(default=0)),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('tarix', models.DateField(editable=False)),
                ('shobe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.shobe')),
            ],
        ),
        migrations.CreateModel(
            name='ShirketGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gunleri_count', models.PositiveBigIntegerField(default=0)),
                ('qeyri_is_gunu_count', models.PositiveBigIntegerField(default=0)),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('tarix', models.DateField(editable=False)),
                ('shirket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.shirket')),
            ],
        ),
        migrations.CreateModel(
            name='OfisGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gunleri_count', models.PositiveBigIntegerField(default=0)),
                ('qeyri_is_gunu_count', models.PositiveBigIntegerField(default=0)),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('tarix', models.DateField(editable=False)),
                ('ofis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.ofis')),
            ],
        ),
        migrations.CreateModel(
            name='KomandaGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gunleri_count', models.PositiveBigIntegerField(default=0)),
                ('qeyri_is_gunu_count', models.PositiveBigIntegerField(default=0)),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('tarix', models.DateField(editable=False)),
                ('komanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.komanda')),
            ],
        ),
        migrations.CreateModel(
            name='HoldingGunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gunleri_count', models.PositiveBigIntegerField(default=0)),
                ('qeyri_is_gunu_count', models.PositiveBigIntegerField(default=0)),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('tarix', models.DateField(editable=False)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_gunleri', to='company.holding')),
            ],
        ),
    ]
