# Generated by Django 3.2.12 on 2022-03-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gunler', '0003_auto_20220330_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdinggunler',
            name='tetil_gunleri',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
