# Generated by Django 3.2.12 on 2022-03-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gunler', '0004_alter_holdinggunler_tetil_gunleri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdinggunler',
            name='tetil_gunleri',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
