# Generated by Django 3.2.12 on 2022-04-01 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gunler', '0005_alter_holdinggunler_tetil_gunleri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holdinggunler',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='iscigunler',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='komandagunler',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='ofisgunler',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='shirketgunler',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='shobegunler',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='vezifegunler',
            options={'ordering': ('pk',)},
        ),
        migrations.AddField(
            model_name='holdinggunler',
            name='istisna_isciler',
            field=models.ManyToManyField(related_name='istisna_isciler', to=settings.AUTH_USER_MODEL),
        ),
    ]
