# Generated by Django 3.2.12 on 2022-04-02 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gunler', '0006_auto_20220401_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='komandagunler',
            name='istisna_isciler',
            field=models.ManyToManyField(related_name='komanda_istisna_isciler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ofisgunler',
            name='istisna_isciler',
            field=models.ManyToManyField(related_name='ofis_istisna_isciler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shirketgunler',
            name='istisna_isciler',
            field=models.ManyToManyField(related_name='shirket_istisna_isciler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shobegunler',
            name='istisna_isciler',
            field=models.ManyToManyField(related_name='shobe_istisna_isciler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vezifegunler',
            name='istisna_isciler',
            field=models.ManyToManyField(related_name='vezife_istisna_isciler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='holdinggunler',
            name='istisna_isciler',
            field=models.ManyToManyField(related_name='holding_istisna_isciler', to=settings.AUTH_USER_MODEL),
        ),
    ]
