# Generated by Django 3.2.12 on 2022-04-02 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gunler', '0007_auto_20220402_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdinggunler',
            name='istisna_isciler',
        ),
        migrations.CreateModel(
            name='HoldingIstisnaIsci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('holding_gunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_istisna_isci', to='gunler.holdinggunler')),
                ('istisna_isciler', models.ManyToManyField(related_name='holding_istisna_isciler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
