# Generated by Django 3.2.12 on 2022-04-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gunler', '0008_auto_20220402_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdinggunler',
            name='tetil_gunleri',
        ),
        migrations.RemoveField(
            model_name='komandagunler',
            name='istisna_isciler',
        ),
        migrations.RemoveField(
            model_name='komandagunler',
            name='tetil_gunleri',
        ),
        migrations.RemoveField(
            model_name='ofisgunler',
            name='istisna_isciler',
        ),
        migrations.RemoveField(
            model_name='ofisgunler',
            name='tetil_gunleri',
        ),
        migrations.RemoveField(
            model_name='shirketgunler',
            name='istisna_isciler',
        ),
        migrations.RemoveField(
            model_name='shirketgunler',
            name='tetil_gunleri',
        ),
        migrations.RemoveField(
            model_name='shobegunler',
            name='istisna_isciler',
        ),
        migrations.RemoveField(
            model_name='shobegunler',
            name='tetil_gunleri',
        ),
        migrations.RemoveField(
            model_name='vezifegunler',
            name='istisna_isciler',
        ),
        migrations.RemoveField(
            model_name='vezifegunler',
            name='tetil_gunleri',
        ),
    ]
