# Generated by Django 3.2.12 on 2022-04-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gunler', '0009_auto_20220402_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holdingistisnaisci',
            options={'ordering': ('pk',)},
        ),
    ]
