# Generated by Django 3.2.12 on 2022-04-03 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gunler', '0010_alter_holdingistisnaisci_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdingistisnaisci',
            name='holding_gunler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istisna_isci', to='gunler.holdinggunler'),
        ),
        migrations.AlterField(
            model_name='holdingistisnaisci',
            name='istisna_isciler',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VezifeIstisnaIsci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('istisna_isciler', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('vezife_gunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istisna_isci', to='gunler.vezifegunler')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ShobeIstisnaIsci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('istisna_isciler', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('shobe_gunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istisna_isci', to='gunler.shobegunler')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ShirketIstisnaIsci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('istisna_isciler', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('shirket_gunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istisna_isci', to='gunler.shirketgunler')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='OfisIstisnaIsci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('istisna_isciler', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('ofis_gunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istisna_isci', to='gunler.ofisgunler')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='KomandaIstisnaIsci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetil_gunleri', models.CharField(blank=True, max_length=500, null=True)),
                ('istisna_isciler', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('komanda_gunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istisna_isci', to='gunler.komandagunler')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
