# Generated by Django 3.2.9 on 2022-03-13 04:17

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mehsullar', '__first__'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('asa', models.CharField(max_length=200)),
                ('dogum_tarixi', models.DateField(blank=True, null=True)),
                ('ishe_baslama_tarixi', models.DateField(auto_now_add=True, null=True)),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('tel1', models.CharField(max_length=200)),
                ('tel2', models.CharField(max_length=200)),
                ('sv_image', models.ImageField(upload_to='media/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'ordering': ('pk',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holding_adi', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='HoldingKassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balans', models.FloatField()),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_kassa', to='account.holding')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Komanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komanda_adi', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asa', models.CharField(max_length=200)),
                ('sv_image', models.ImageField(upload_to='media/')),
                ('tel1', models.CharField(max_length=50)),
                ('tel2', models.CharField(max_length=50)),
                ('tel3', models.CharField(max_length=50)),
                ('tel4', models.CharField(max_length=50)),
                ('unvan', models.TextField()),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Ofis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofis_adi', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='OfisKassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balans', models.FloatField()),
                ('ofis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofis_kassa', to='account.ofis')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Shirket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirket_adi', models.CharField(max_length=200, unique=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='holding_shirket', to='account.holding')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Shobe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shobe_adi', models.CharField(max_length=200)),
                ('ofis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shobe', to='account.ofis')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Vezifeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vezife_adi', models.CharField(max_length=50)),
                ('shirket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirket_vezifeleri', to='account.shirket')),
                ('shobe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shobe_vezife', to='account.shobe')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ShirketKassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balans', models.FloatField()),
                ('shirket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirket_kassa', to='account.shirket')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ShirketdenOfislereTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_meblegi', models.FloatField()),
                ('transfer_tarixi', models.DateField(auto_now=True)),
                ('transfer_qeydi', models.TextField(blank=True, null=True)),
                ('ofis_kassa', models.ManyToManyField(related_name='shirketden_ofise_transfer', to='account.OfisKassa')),
                ('shirket_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirketden_ofise_transfer', to='account.shirketkassa')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ShirketdenHoldingeTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_meblegi', models.FloatField()),
                ('transfer_tarixi', models.DateField(auto_now=True)),
                ('transfer_qeydi', models.TextField(blank=True, null=True)),
                ('holding_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirketden_holdinge_transfer', to='account.holdingkassa')),
                ('shirket_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirketden_holdinge_transfer', to='account.shirketkassa')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='OfisdenShirketeTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_meblegi', models.FloatField()),
                ('transfer_tarixi', models.DateField(auto_now=True)),
                ('transfer_qeydi', models.TextField(blank=True, null=True)),
                ('ofis_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofisden_shirkete_transfer', to='account.ofiskassa')),
                ('shirket_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofisden_shirkete_transfer', to='account.shirketkassa')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.AddField(
            model_name='ofis',
            name='shirket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirket_ofis', to='account.shirket'),
        ),
        migrations.CreateModel(
            name='MusteriQeydler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basliq', models.CharField(max_length=100)),
                ('qeyd', models.TextField()),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musteri_qeydler', to='account.musteri')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Maas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maas_uslubu', models.CharField(choices=[('FIX', 'FIX'), ('BONUS', 'BONUS'), ('BONUS-FIX', 'BONUS-FIX')], default='FIX', max_length=20)),
                ('verilecek_maas', models.FloatField(blank=True, null=True)),
                ('maas_tarixi', models.DateField(blank=True, null=True)),
                ('odenme_status', models.BooleanField(default=False)),
                ('isci', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='isci_maas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='HoldingdenShirketlereTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_meblegi', models.FloatField()),
                ('transfer_tarixi', models.DateField(auto_now=True)),
                ('transfer_qeydi', models.TextField(blank=True, null=True)),
                ('holding_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holdingden_shirkete_transfer', to='account.holdingkassa')),
                ('shirket_kassa', models.ManyToManyField(related_name='holdingden_shirkete_transfer', to='account.ShirketKassa')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=250, null=True)),
                ('satis_meblegi', models.FloatField(default=0)),
                ('odenis_uslubu', models.CharField(choices=[('KREDIT', 'KREDIT'), ('NAGD', 'NAGD')], default='NAGD', max_length=20)),
                ('komandaya_gore_bonus', models.FloatField(blank=True, default=0, null=True)),
                ('ofise_gore_bonus', models.FloatField(blank=True, default=0, null=True)),
                ('stok', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stok_bonus', to='mehsullar.stok')),
                ('vezife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vezife_bonus', to='account.vezifeler')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='komanda',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_komanda', to='account.komanda'),
        ),
        migrations.AddField(
            model_name='user',
            name='ofis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ishci', to='account.ofis'),
        ),
        migrations.AddField(
            model_name='user',
            name='shirket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ishci', to='account.shirket'),
        ),
        migrations.AddField(
            model_name='user',
            name='shobe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ishci', to='account.shobe'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.bonus'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='vezife',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_vezife', to='account.vezifeler'),
        ),
    ]
