# Generated by Django 3.2.9 on 2022-02-18 08:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holding_adi', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Komanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komanda_adi', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asa', models.CharField(max_length=200)),
                ('sv_image', models.ImageField(upload_to='media/')),
                ('tel1', models.CharField(max_length=50)),
                ('tel2', models.CharField(max_length=50)),
                ('tel3', models.CharField(max_length=50)),
                ('tel4', models.CharField(max_length=50)),
                ('unvan', models.TextField()),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Ofis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofis_adi', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Shirket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirket_adi', models.CharField(max_length=200, unique=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='holding_shirket', to='account.holding')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Shobe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shobe_adi', models.CharField(max_length=200)),
                ('ofis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shobe', to='account.ofis')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Vezifeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vezife_adi', models.CharField(max_length=50)),
                ('shirket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirket_vezifeleri', to='account.shirket')),
                ('shobe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shobe_vezife', to='account.shobe')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ShirketKassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balans', models.FloatField()),
                ('shirket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirket_kassa', to='account.shirket')),
            ],
        ),
        migrations.CreateModel(
            name='ShirketdenOfislereTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_meblegi', models.FloatField()),
                ('transfer_tarixi', models.DateField(auto_now=True)),
                ('transfer_qeydi', models.TextField(blank=True, null=True)),
                ('ofis', models.ManyToManyField(related_name='shirketden_ofise_transfer', to='account.Ofis')),
                ('shirket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirketden_ofise_transfer', to='account.shirket')),
            ],
        ),
        migrations.CreateModel(
            name='ShirketdenHoldingeTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_meblegi', models.FloatField()),
                ('transfer_tarixi', models.DateField(auto_now=True)),
                ('transfer_qeydi', models.TextField(blank=True, null=True)),
                ('holding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirketden_holdinge_transfer', to='account.holding')),
                ('shirket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirketden_holdinge_transfer', to='account.shirket')),
            ],
        ),
        migrations.CreateModel(
            name='OfisKassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balans', models.FloatField()),
                ('ofis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofis_kassa', to='account.ofis')),
            ],
        ),
        migrations.CreateModel(
            name='OfisdenShirketeTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_meblegi', models.FloatField()),
                ('transfer_tarixi', models.DateField(auto_now=True)),
                ('transfer_qeydi', models.TextField(blank=True, null=True)),
                ('ofis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofisden_shirkete_transfer', to='account.ofis')),
                ('shirket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofisden_shirkete_transfer', to='account.shirket')),
            ],
        ),
        migrations.AddField(
            model_name='ofis',
            name='shirket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirket_ofis', to='account.shirket'),
        ),
        migrations.CreateModel(
            name='MusteriQeydler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basliq', models.CharField(max_length=100)),
                ('qeyd', models.TextField()),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musteri_qeydler', to='account.musteri')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='HoldingKassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balans', models.FloatField()),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_kassa', to='account.holding')),
            ],
        ),
        migrations.CreateModel(
            name='HoldingdenShirketlereTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_meblegi', models.FloatField()),
                ('transfer_tarixi', models.DateField(auto_now=True)),
                ('transfer_qeydi', models.TextField(blank=True, null=True)),
                ('holding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holdingden_shirkete_transfer', to='account.holding')),
                ('shirket', models.ManyToManyField(related_name='holdingden_shirkete_transfer', to='account.Shirket')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('asa', models.CharField(max_length=200)),
                ('maas', models.FloatField(default=0)),
                ('dogum_tarixi', models.DateField(blank=True, null=True)),
                ('ishe_baslama_tarixi', models.DateField(auto_now_add=True, null=True)),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('tel1', models.CharField(max_length=200)),
                ('tel2', models.CharField(max_length=200)),
                ('sv_image', models.ImageField(upload_to='media/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('komanda', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_komanda', to='account.komanda')),
                ('ofis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ishci', to='account.ofis')),
                ('shirket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ishci', to='account.shirket')),
                ('shobe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ishci', to='account.shobe')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('vezife', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_vezife', to='account.vezifeler')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
