# Generated by Django 3.2.9 on 2022-02-18 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdingdenshirketleretransfer',
            name='holding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holdingden_shirkete_transfer', to='account.holdingkassa'),
        ),
        migrations.AlterField(
            model_name='holdingdenshirketleretransfer',
            name='shirket',
            field=models.ManyToManyField(related_name='holdingden_shirkete_transfer', to='account.ShirketKassa'),
        ),
        migrations.AlterField(
            model_name='ofisdenshirketetransfer',
            name='ofis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofisden_shirkete_transfer', to='account.ofiskassa'),
        ),
        migrations.AlterField(
            model_name='ofisdenshirketetransfer',
            name='shirket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofisden_shirkete_transfer', to='account.shirketkassa'),
        ),
        migrations.AlterField(
            model_name='shirketdenholdingetransfer',
            name='holding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirketden_holdinge_transfer', to='account.holdingkassa'),
        ),
        migrations.AlterField(
            model_name='shirketdenholdingetransfer',
            name='shirket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirketden_holdinge_transfer', to='account.shirketkassa'),
        ),
        migrations.AlterField(
            model_name='shirketdenofisleretransfer',
            name='ofis',
            field=models.ManyToManyField(related_name='shirketden_ofise_transfer', to='account.OfisKassa'),
        ),
        migrations.AlterField(
            model_name='shirketdenofisleretransfer',
            name='shirket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirketden_ofise_transfer', to='account.shirketkassa'),
        ),
    ]
