# Generated by Django 3.2.9 on 2021-12-24 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musteri',
            name='musteri_qeydi',
        ),
        migrations.CreateModel(
            name='MusteriQeydler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basliq', models.CharField(max_length=100)),
                ('qeyd', models.TextField()),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musteri_qeydler', to='account.musteri')),
            ],
        ),
    ]
