# Generated by Django 3.2.12 on 2022-04-06 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_holdingdenshirketleretransfer_holdingkassamedaxil_holdingkassamexaric_ofisdenshirketetransfer_ofiska'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='komanda',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_komanda', to='company.komanda'),
        ),
        migrations.AddField(
            model_name='user',
            name='ofis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ishci', to='company.ofis'),
        ),
        migrations.AddField(
            model_name='user',
            name='shirket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ishci', to='company.shirket'),
        ),
        migrations.AddField(
            model_name='user',
            name='shobe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ishci', to='company.shobe'),
        ),
        migrations.AddField(
            model_name='user',
            name='vezife',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_vezife', to='company.vezifeler'),
        ),
    ]
