# Generated by Django 3.2.9 on 2022-02-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_komanda_komanda_adi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirket',
            name='shirket_adi',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
