# Generated by Django 3.2.9 on 2022-03-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_bonus_stok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sv_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
