# Generated by Django 3.2.9 on 2022-02-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220218_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holdingdenshirketleretransfer',
            old_name='holding',
            new_name='holding_kassa',
        ),
        migrations.RenameField(
            model_name='holdingdenshirketleretransfer',
            old_name='shirket',
            new_name='shirket_kassa',
        ),
        migrations.RenameField(
            model_name='ofisdenshirketetransfer',
            old_name='ofis',
            new_name='ofis_kassa',
        ),
        migrations.RenameField(
            model_name='ofisdenshirketetransfer',
            old_name='shirket',
            new_name='shirket_kassa',
        ),
        migrations.RenameField(
            model_name='shirketdenholdingetransfer',
            old_name='holding',
            new_name='holding_kassa',
        ),
        migrations.RenameField(
            model_name='shirketdenholdingetransfer',
            old_name='shirket',
            new_name='shirket_kassa',
        ),
        migrations.RenameField(
            model_name='shirketdenofisleretransfer',
            old_name='ofis',
            new_name='ofis_kassa',
        ),
        migrations.RenameField(
            model_name='shirketdenofisleretransfer',
            old_name='shirket',
            new_name='shirket_kassa',
        ),
    ]
