# Generated by Django 3.2.12 on 2022-04-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220406_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='maas',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
