# Generated by Django 3.2.9 on 2021-12-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_dogum_tarixi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ishe_baslama_tarixi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
