# Generated by Django 3.2.9 on 2022-03-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_sv_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musteriqeydler',
            name='basliq',
        ),
        migrations.AlterField(
            model_name='musteri',
            name='tel2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='tel3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='tel4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
