# Generated by Django 3.2.9 on 2022-02-24 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220224_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='vezife',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vezife_bonus', to='account.vezifeler'),
        ),
    ]
