# Generated by Django 3.2.9 on 2022-02-28 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_bonus_vezife'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='holdingdenshirketleretransfer',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='holdingkassa',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='maas',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='ofisdenshirketetransfer',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='ofiskassa',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='shirketdenholdingetransfer',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='shirketdenofisleretransfer',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='shirketkassa',
            options={'ordering': ('pk',)},
        ),
    ]
