# Generated by Django 3.2.12 on 2022-03-15 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_holdingdenshirketleretransfer_holdingkassamedaxil_holdingkassamexaric_ofisdenshirketetransfer_ofiska'),
        ('account', '0004_user_maas_uslubu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ofis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ishci', to='company.ofis'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shirket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ishci', to='company.shirket'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shobe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ishci', to='company.shobe'),
        ),
    ]
