# Generated by Django 3.2.12 on 2022-05-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220315_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteri',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
