# Generated by Django 3.2.9 on 2021-12-30 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211229_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vezifeler',
            name='merkez',
        ),
        migrations.CreateModel(
            name='Shobe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shobe_adi', models.CharField(max_length=200)),
                ('merkez', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shobe', to='account.merkezler')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='shobe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ishci', to='account.shobe'),
        ),
        migrations.AddField(
            model_name='vezifeler',
            name='shobe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shobe_vezife', to='account.shobe'),
        ),
    ]
