# Generated by Django 3.2.9 on 2022-03-15 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('mehsullar', '0007_auto_20220315_1245'),
        ('account', '0006_iscisatissayi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdingdenshirketleretransfer',
            name='holding_kassa',
        ),
        migrations.RemoveField(
            model_name='holdingdenshirketleretransfer',
            name='shirket_kassa',
        ),
        migrations.RemoveField(
            model_name='holdingkassa',
            name='holding',
        ),
        migrations.RemoveField(
            model_name='ofis',
            name='shirket',
        ),
        migrations.RemoveField(
            model_name='ofisdenshirketetransfer',
            name='ofis_kassa',
        ),
        migrations.RemoveField(
            model_name='ofisdenshirketetransfer',
            name='shirket_kassa',
        ),
        migrations.RemoveField(
            model_name='ofiskassa',
            name='ofis',
        ),
        migrations.RemoveField(
            model_name='shirket',
            name='holding',
        ),
        migrations.RemoveField(
            model_name='shirketdenholdingetransfer',
            name='holding_kassa',
        ),
        migrations.RemoveField(
            model_name='shirketdenholdingetransfer',
            name='shirket_kassa',
        ),
        migrations.RemoveField(
            model_name='shirketdenofisleretransfer',
            name='ofis_kassa',
        ),
        migrations.RemoveField(
            model_name='shirketdenofisleretransfer',
            name='shirket_kassa',
        ),
        migrations.RemoveField(
            model_name='shirketkassa',
            name='shirket',
        ),
        migrations.RemoveField(
            model_name='shobe',
            name='ofis',
        ),
        migrations.RemoveField(
            model_name='vezifeler',
            name='shirket',
        ),
        migrations.RemoveField(
            model_name='vezifeler',
            name='shobe',
        ),
        migrations.AlterField(
            model_name='bonus',
            name='vezife',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vezife_bonus', to='company.vezifeler'),
        ),
        migrations.AlterField(
            model_name='user',
            name='komanda',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_komanda', to='company.komanda'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ofis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ishci', to='company.ofis'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shirket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ishci', to='company.shirket'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shobe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ishci', to='company.shobe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vezife',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_vezife', to='company.vezifeler'),
        ),
        migrations.DeleteModel(
            name='Holding',
        ),
        migrations.DeleteModel(
            name='HoldingdenShirketlereTransfer',
        ),
        migrations.DeleteModel(
            name='HoldingKassa',
        ),
        migrations.DeleteModel(
            name='Komanda',
        ),
        migrations.DeleteModel(
            name='Ofis',
        ),
        migrations.DeleteModel(
            name='OfisdenShirketeTransfer',
        ),
        migrations.DeleteModel(
            name='OfisKassa',
        ),
        migrations.DeleteModel(
            name='Shirket',
        ),
        migrations.DeleteModel(
            name='ShirketdenHoldingeTransfer',
        ),
        migrations.DeleteModel(
            name='ShirketdenOfislereTransfer',
        ),
        migrations.DeleteModel(
            name='ShirketKassa',
        ),
        migrations.DeleteModel(
            name='Shobe',
        ),
        migrations.DeleteModel(
            name='Vezifeler',
        ),
    ]
