# Generated by Django 3.2.9 on 2021-12-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20211230_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musteri',
            name='unvan',
            field=models.TextField(),
        ),
    ]
