# Generated by Django 3.2.9 on 2022-03-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220315_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musteri',
            name='sv_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sv_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
