# Generated by Django 3.2.9 on 2022-01-18 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_musteri_unvan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vezifeler',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='vezife',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_vezife', to='account.vezifeler'),
        ),
    ]
