# Generated by Django 3.2.12 on 2022-04-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_komanda_is_active'),
        ('account', '0008_auto_20220417_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vezife',
            field=models.ManyToManyField(blank=True, related_name='user_vezife', to='company.Vezifeler'),
        ),
    ]
