# Generated by Django 3.2.9 on 2022-03-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20220315_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iscisatissayi',
            options={'ordering': ('pk',)},
        ),
    ]
