# Generated by Django 3.2.9 on 2022-03-21 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_iscisatissayi_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_adi', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='stok',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='vezife',
        ),
        migrations.DeleteModel(
            name='Maas',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.status'),
        ),
        migrations.DeleteModel(
            name='Bonus',
        ),
    ]
