# Generated by Django 3.2.12 on 2022-03-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maas', '0003_rename_status_prim_prim_status'),
        ('account', '0010_auto_20220321_1627'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='IsciStatus',
        ),
    ]
