# Generated by Django 3.2.12 on 2022-04-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_ishe_baslama_tarixi'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteriqeydler',
            name='tarix',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
