# Generated by Django 3.2.12 on 2022-03-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_rename_status_iscistatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='isci_status',
        ),
    ]
