# Generated by Django 3.2.12 on 2022-04-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_musteriqeydler_tarix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='maas',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
