# Generated by Django 3.2.9 on 2022-01-21 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vezife',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_vezife', to='account.vezifeler'),
        ),
    ]
