# Generated by Django 3.2.9 on 2022-01-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_user_vezife'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komanda_adi', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='komanda',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_komanda', to='account.komanda'),
        ),
    ]
