version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: django_celery_example_web
    # '/start' is the shell script used to run the service
    command: python3 manage.py runserver 0.0.0.0:8000
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    ports:
      - 8010:8000
    # env_file is used to manage the env variables of our project
    depends_on:
      - redis
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=crm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:6-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: django_celery_example_celery_worker
    command: celery -A core worker --beat --scheduler django --loglevel=info 
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: django_celery_example_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: django_celery_example_celery_flower
    command: celery -A core flower  --address=127.0.0.1 --port=5566
    volumes:
      - .:/app
    ports:
      - 5566:5566
    depends_on:
      - redis
      - db

volumes:
  postgres_data: