# Generated by Django 3.2.9 on 2022-03-21 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0009_auto_20220316_1813'),
        ('mehsullar', '0013_auto_20220321_1102'),
        ('account', '0010_auto_20220321_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaasGoruntuleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satis_sayi', models.PositiveBigIntegerField(blank=True, default=0)),
                ('satis_meblegi', models.FloatField(blank=True, default=0)),
                ('yekun_maas', models.FloatField(blank=True, default=0)),
                ('isci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isci_maas_goruntuleme', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maas_uslubu', models.CharField(choices=[('FIX', 'FIX'), ('BONUS', 'BONUS'), ('BONUS-FIX', 'BONUS-FIX')], default='FIX', max_length=20)),
                ('verilecek_maas', models.FloatField(blank=True, null=True)),
                ('maas_tarixi', models.DateField(blank=True, null=True)),
                ('odenme_status', models.BooleanField(default=False)),
                ('isci', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='isci_maas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Kesinti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mebleg', models.FloatField(blank=True, default=0)),
                ('qeyd', models.TextField()),
                ('kesinti_tarixi', models.DateField()),
                ('isci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isci_kesinti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('kesinti_tarixi',),
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satis_meblegi', models.FloatField(default=0)),
                ('odenis_uslubu', models.CharField(choices=[('KREDIT', 'KREDIT'), ('NAGD', 'NAGD')], default='NAGD', max_length=20)),
                ('komandaya_gore_bonus', models.FloatField(blank=True, default=0, null=True)),
                ('ofise_gore_bonus', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.status')),
                ('stok', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stok_bonus', to='mehsullar.stok')),
                ('vezife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vezife_bonus', to='company.vezifeler')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Avans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mebleg', models.FloatField(blank=True, default=0)),
                ('yarim_ay_emek_haqqi', models.PositiveBigIntegerField(blank=True, default=0)),
                ('qeyd', models.TextField()),
                ('avans_tarixi', models.DateField()),
                ('isci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isci_avans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('avans_tarixi',),
            },
        ),
    ]
