# Generated by Django 3.2.12 on 2022-04-06 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mehsullar', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='VanLeaderPrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satis_meblegi', models.FloatField(default=0)),
                ('odenis_uslubu', models.CharField(choices=[('KREDİT', 'KREDİT'), ('NƏĞD', 'NƏĞD')], default='NƏĞD', max_length=20)),
                ('komandaya_gore_prim', models.FloatField(blank=True, default=0, null=True)),
                ('mehsul', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mehsullar.mehsullar')),
                ('prim_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.iscistatus')),
                ('vezife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.vezifeler')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeLeaderPrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satis_meblegi', models.FloatField(default=0)),
                ('odenis_uslubu', models.CharField(choices=[('KREDİT', 'KREDİT'), ('NƏĞD', 'NƏĞD')], default='NƏĞD', max_length=20)),
                ('ofise_gore_prim', models.FloatField(blank=True, default=0, null=True)),
                ('mehsul', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mehsullar.mehsullar')),
                ('prim_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.iscistatus')),
                ('vezife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.vezifeler')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaasGoruntuleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satis_sayi', models.PositiveBigIntegerField(blank=True, default=0)),
                ('satis_meblegi', models.FloatField(blank=True, default=0)),
                ('yekun_maas', models.FloatField(blank=True, default=0)),
                ('tarix', models.DateField(auto_now_add=True, null=True)),
                ('isci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isci_maas_goruntuleme', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Kesinti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mebleg', models.FloatField(blank=True, default=0)),
                ('qeyd', models.TextField()),
                ('kesinti_tarixi', models.DateField()),
                ('isci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isci_kesinti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('kesinti_tarixi',),
            },
        ),
        migrations.CreateModel(
            name='DealerPrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satis_meblegi', models.FloatField(default=0)),
                ('odenis_uslubu', models.CharField(choices=[('KREDİT', 'KREDİT'), ('NƏĞD', 'NƏĞD')], default='NƏĞD', max_length=20)),
                ('komandaya_gore_prim', models.FloatField(blank=True, default=0, null=True)),
                ('mehsul', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mehsullar.mehsullar')),
                ('prim_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.iscistatus')),
                ('vezife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.vezifeler')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CanvasserPrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satis_meblegi', models.FloatField(default=0)),
                ('odenis_uslubu', models.CharField(choices=[('KREDİT', 'KREDİT'), ('NƏĞD', 'NƏĞD')], default='NƏĞD', max_length=20)),
                ('satis9_14', models.FloatField(blank=True, default=0, null=True)),
                ('satis15p', models.FloatField(blank=True, default=0, null=True)),
                ('satis20p', models.FloatField(blank=True, default=0, null=True)),
                ('komandaya_gore_prim', models.FloatField(blank=True, default=0, null=True)),
                ('ofise_gore_prim', models.FloatField(blank=True, default=0, null=True)),
                ('mehsul', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mehsullar.mehsullar')),
                ('prim_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.iscistatus')),
                ('vezife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.vezifeler')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Avans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mebleg', models.FloatField(blank=True, default=0)),
                ('yarim_ay_emek_haqqi', models.PositiveBigIntegerField(blank=True, default=0)),
                ('qeyd', models.TextField()),
                ('avans_tarixi', models.DateField()),
                ('isci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isci_avans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('avans_tarixi',),
            },
        ),
    ]
