# Generated by Django 3.2.12 on 2022-03-23 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0013_auto_20220321_1102'),
        ('account', '0010_auto_20220321_1627'),
        ('company', '0009_auto_20220316_1813'),
        ('maas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satis_meblegi', models.FloatField(default=0)),
                ('odenis_uslubu', models.CharField(choices=[('KREDİT', 'KREDİT'), ('NƏĞD', 'NƏĞD')], default='NƏĞD', max_length=20)),
                ('komandaya_gore_bonus', models.FloatField(blank=True, default=0, null=True)),
                ('ofise_gore_bonus', models.FloatField(blank=True, default=0, null=True)),
                ('mehsul', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mehsul_prim', to='mehsullar.mehsullar')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_prim', to='account.status')),
                ('vezife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vezife_prim', to='company.vezifeler')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.RemoveField(
            model_name='maas',
            name='isci',
        ),
        migrations.AlterModelOptions(
            name='maasgoruntuleme',
            options={'ordering': ('pk',)},
        ),
        migrations.AddField(
            model_name='maasgoruntuleme',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Bonus',
        ),
        migrations.DeleteModel(
            name='Maas',
        ),
    ]
