# Generated by Django 3.2.12 on 2022-03-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maas', '0002_auto_20220323_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prim',
            old_name='status',
            new_name='prim_status',
        ),
    ]
