# Generated by Django 3.2.12 on 2022-03-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maas', '0003_rename_status_prim_prim_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maasgoruntuleme',
            old_name='created',
            new_name='tarix',
        ),
    ]
