# Generated by Django 3.2.12 on 2022-04-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maas', '0003_alter_maasgoruntuleme_tarix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maasgoruntuleme',
            name='tarix',
            field=models.DateField(blank=True, null=True),
        ),
    ]
