# Generated by Django 3.2.12 on 2022-03-24 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_rename_status_user_isci_status'),
        ('maas', '0005_auto_20220324_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerprim',
            name='prim_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.iscistatus'),
        ),
        migrations.AlterField(
            model_name='vanleaderprim',
            name='prim_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.iscistatus'),
        ),
    ]
