# Generated by Django 3.2.12 on 2022-04-15 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maas', '0005_alter_maasgoruntuleme_tarix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maasgoruntuleme',
            name='tarix',
            field=models.DateField(blank=True, default=datetime.date(2022, 4, 15), null=True),
        ),
    ]
