# Generated by Django 3.2.12 on 2022-03-25 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20220316_1813'),
        ('mehsullar', '0013_auto_20220321_1102'),
        ('account', '0012_rename_status_user_isci_status'),
        ('maas', '0006_auto_20220324_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLeaderPrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satis_meblegi', models.FloatField(default=0)),
                ('odenis_uslubu', models.CharField(choices=[('KREDİT', 'KREDİT'), ('NƏĞD', 'NƏĞD')], default='NƏĞD', max_length=20)),
                ('ofise_gore_prim', models.FloatField(blank=True, default=0, null=True)),
                ('mehsul', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mehsullar.mehsullar')),
                ('prim_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.iscistatus')),
                ('vezife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.vezifeler')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CanvasserPrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satis_meblegi', models.FloatField(default=0)),
                ('odenis_uslubu', models.CharField(choices=[('KREDİT', 'KREDİT'), ('NƏĞD', 'NƏĞD')], default='NƏĞD', max_length=20)),
                ('satis9_14', models.FloatField(blank=True, default=0, null=True)),
                ('satis15p', models.FloatField(blank=True, default=0, null=True)),
                ('satis20p', models.FloatField(blank=True, default=0, null=True)),
                ('komandaya_gore_prim', models.FloatField(blank=True, default=0, null=True)),
                ('ofise_gore_prim', models.FloatField(blank=True, default=0, null=True)),
                ('mehsul', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mehsullar.mehsullar')),
                ('prim_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.iscistatus')),
                ('vezife', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.vezifeler')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
