# Generated by Django 3.2.12 on 2022-03-15 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maas', '0008_auto_20220415_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avans',
            name='avans_tarixi',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='kesinti',
            name='kesinti_tarixi',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
