# Generated by Django 3.2.12 on 2022-04-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maas', '0009_auto_20220315_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasserprim',
            name='fix_maas',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='canvasserprim',
            name='satis1_8',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dealerprim',
            name='fix_maas',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='officeleaderprim',
            name='fix_maas',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vanleaderprim',
            name='fix_maas',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
