# Generated by Django 3.2.12 on 2022-04-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maas', '0012_auto_20220412_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvasserprim',
            name='odenis_uslubu',
        ),
        migrations.RemoveField(
            model_name='officeleaderprim',
            name='odenis_uslubu',
        ),
    ]
