# Generated by Django 3.2.12 on 2022-04-17 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maas', '0013_auto_20220412_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaasOde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mebleg', models.FloatField(blank=True, default=0)),
                ('qeyd', models.TextField()),
                ('odeme_tarixi', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('isci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maas_ode', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('odeme_tarixi',),
            },
        ),
    ]
