# Generated by Django 3.2.9 on 2022-03-13 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('ofis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofis_anbar', to='account.ofis')),
                ('shirket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirket_anbar', to='account.shirket')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Hediyye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hediyye_adi', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Mehsullar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mehsulun_adi', models.CharField(max_length=300)),
                ('qiymet', models.FloatField()),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Muqavile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mehsul_sayi', models.PositiveIntegerField(blank=True, default=1)),
                ('muqavile_umumi_mebleg', models.FloatField(blank=True, default=0)),
                ('elektron_imza', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('muqavile_tarixi', models.DateField(auto_now_add=True, null=True)),
                ('odenis_uslubu', models.CharField(choices=[('NƏĞD', 'NƏĞD'), ('KREDİT', 'KREDİT'), ('İKİ DƏFƏYƏ NƏĞD', 'İKİ DƏFƏYƏ NƏĞD')], default='NƏĞD', max_length=20)),
                ('negd_odenis_1', models.FloatField(blank=True, default=0)),
                ('negd_odenis_2', models.FloatField(blank=True, default=0)),
                ('negd_odenis_1_tarix', models.DateField(blank=True, null=True)),
                ('negd_odenis_2_tarix', models.DateField(blank=True, null=True)),
                ('negd_odenis_1_status', models.CharField(choices=[('YOXDUR', 'YOXDUR'), ('BİTMİŞ', 'BİTMİŞ'), ('DAVAM EDƏN', 'DAVAM EDƏN')], default='YOXDUR', max_length=20)),
                ('negd_odenis_2_status', models.CharField(choices=[('YOXDUR', 'YOXDUR'), ('BİTMİŞ', 'BİTMİŞ'), ('DAVAM EDƏN', 'DAVAM EDƏN')], default='YOXDUR', max_length=20)),
                ('muqavile_status', models.CharField(choices=[('DAVAM EDƏN', 'DAVAM EDƏN'), ('BİTMİŞ', 'BİTMİŞ'), ('LƏĞV OLUNMUŞ', 'LƏĞV OLUNMUŞ')], default='DAVAM EDƏN', max_length=20)),
                ('kredit_muddeti', models.IntegerField(blank=True, default=0)),
                ('ilkin_odenis', models.FloatField(blank=True, default=0)),
                ('ilkin_odenis_qaliq', models.FloatField(blank=True, default=0)),
                ('ilkin_odenis_tarixi', models.DateField(blank=True, null=True)),
                ('ilkin_odenis_qaliq_tarixi', models.DateField(blank=True, null=True)),
                ('ilkin_odenis_status', models.CharField(choices=[('YOXDUR', 'YOXDUR'), ('BİTMİŞ', 'BİTMİŞ'), ('DAVAM EDƏN', 'DAVAM EDƏN')], default='YOXDUR', max_length=20)),
                ('qaliq_ilkin_odenis_status', models.CharField(choices=[('YOXDUR', 'YOXDUR'), ('BİTMİŞ', 'BİTMİŞ'), ('DAVAM EDƏN', 'DAVAM EDƏN')], default='YOXDUR', max_length=20)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('canvesser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canvesser', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer', to=settings.AUTH_USER_MODEL)),
                ('hediyye1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile_hediyye1', to='mehsullar.mehsullar')),
                ('hediyye2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile_hediyye2', to='mehsullar.mehsullar')),
                ('hediyye3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile_hediyye3', to='mehsullar.mehsullar')),
                ('mehsul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mehsul_muqavile', to='mehsullar.mehsullar')),
                ('musteri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musteri_muqavile', to='account.musteri')),
                ('ofis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile', to='account.ofis')),
                ('shirket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile', to='account.shirket')),
                ('shobe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile', to='account.shobe')),
                ('vanleader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vanleader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('say', models.IntegerField(default=0)),
                ('anbar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mehsullar.anbar')),
                ('mehsul', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mehsullar.mehsullar')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Servis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servis_tarix6ay', models.DateField(blank=True, default=False, null=True)),
                ('servis_tarix18ay', models.DateField(blank=True, default=False, null=True)),
                ('servis_tarix24ay', models.DateField(blank=True, default=False, null=True)),
                ('kartric1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kartric1_servis', to='mehsullar.mehsullar')),
                ('kartric2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kartric2_servis', to='mehsullar.mehsullar')),
                ('kartric3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kartric3_servis', to='mehsullar.mehsullar')),
                ('kartric4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kartric4_servis', to='mehsullar.mehsullar')),
                ('kartric5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kartric5_servis', to='mehsullar.mehsullar')),
                ('kartric6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kartric6_servis', to='mehsullar.mehsullar')),
                ('muqavile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servis', to='mehsullar.muqavile')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='OdemeTarix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarix', models.DateField(blank=True, default=False, null=True)),
                ('qiymet', models.FloatField(blank=True, default=0)),
                ('odenme_status', models.CharField(choices=[('ÖDƏNMƏYƏN', 'ÖDƏNMƏYƏN'), ('ÖDƏNƏN', 'ÖDƏNƏN'), ('BURAXILMIŞ AY', 'BURAXILMIŞ AY'), ('NATAMAM AY', 'NATAMAM AY'), ('RAZILAŞDIRILMIŞ AZ ÖDƏMƏ', 'RAZILAŞDIRILMIŞ AZ ÖDƏMƏ'), ('YENİ QRAFİK', 'YENİ QRAFİK'), ('ARTIQ ÖDƏMƏ', 'ARTIQ ÖDƏMƏ'), ('SON AYIN BÖLÜNMƏSİ', 'SON AYIN BÖLÜNMƏSİ')], default='ÖDƏNMƏYƏN', max_length=30)),
                ('gecikdirme_status', models.CharField(blank=True, choices=[('GECİKDİRMƏ', 'GECİKDİRMƏ')], default=None, max_length=30, null=True)),
                ('buraxilmis_ay_alt_status', models.CharField(blank=True, choices=[('SIFIR NÖVBƏTİ AY', 'SIFIR NÖVBƏTİ AY'), ('SIFIR SONUNCU AY', 'SIFIR SONUNCU AY'), ('SIFIR DİGƏR AYLAR', 'SIFIR DİGƏR AYLAR')], default=None, max_length=20, null=True)),
                ('natamam_ay_alt_status', models.CharField(blank=True, choices=[('NATAMAM NÖVBƏTİ AY', 'NATAMAM NÖVBƏTİ AY'), ('NATAMAM SONUNCU AY', 'NATAMAM SONUNCU AY'), ('NATAMAM DİGƏR AYLAR', 'NATAMAM DİGƏR AYLAR')], default=None, max_length=20, null=True)),
                ('artiq_odeme_alt_status', models.CharField(blank=True, choices=[('ARTIQ_BİR_AY', 'ARTIQ_BİR_AY'), ('ARTIQ_BÜTÜN_AYLAR', 'ARTIQ_BÜTÜN_AYLAR')], default=None, max_length=20, null=True)),
                ('muqavile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odeme_tarixi', to='mehsullar.muqavile')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Emeliyyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mehsulun_sayi', models.IntegerField(default=0)),
                ('qeyd', models.TextField(blank=True, default='', null=True)),
                ('emeliyyat_tarixi', models.DateTimeField(auto_now_add=True, null=True)),
                ('gonderen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gonderen', to='mehsullar.anbar')),
                ('gonderilen_mehsul', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_mehsul', to='mehsullar.mehsullar')),
                ('qebul_eden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qebul_eden', to='mehsullar.anbar')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='AnbarQeydler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basliq', models.CharField(max_length=100)),
                ('qeyd', models.TextField()),
                ('anbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anbar_qeyd', to='mehsullar.anbar')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
