# Generated by Django 3.2.9 on 2022-02-08 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('ofis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofis_anbar', to='account.ofis')),
                ('shirket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirket_anbar', to='account.shirket')),
            ],
        ),
        migrations.CreateModel(
            name='Hediyye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hediyye_adi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mehsullar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mehsulun_adi', models.CharField(max_length=300)),
                ('qiymet', models.FloatField()),
                ('anbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anbar_mehsul', to='mehsullar.anbar')),
                ('shirket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mehsul', to='account.shirket')),
            ],
        ),
        migrations.CreateModel(
            name='Muqavile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elektron_imza', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('muqavile_tarixi', models.DateField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('dusen', models.BooleanField(default=False)),
                ('odenis_uslubu', models.BooleanField(default=True)),
                ('ilkin_odenis', models.FloatField(blank=True, null=True)),
                ('ilkin_odenis_tarixi', models.DateField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('canvesser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canvesser', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer', to=settings.AUTH_USER_MODEL)),
                ('hediyye1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile_hediyye1', to='mehsullar.hediyye')),
                ('hediyye2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile_hediyye2', to='mehsullar.hediyye')),
                ('hediyye3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile_hediyye3', to='mehsullar.hediyye')),
                ('mehsul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mehsul_muqavile', to='mehsullar.mehsullar')),
                ('musteri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musteri_muqavile', to='account.musteri')),
                ('ofis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile', to='account.ofis')),
                ('shirket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile', to='account.shirket')),
                ('shobe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile', to='account.shobe')),
                ('vanleader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vanleader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('say', models.IntegerField(default=0)),
                ('anbar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mehsullar.anbar')),
                ('mehsul', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mehsullar.mehsullar')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Servis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servis_tarix6ay', models.DateField(blank=True, default=False, null=True)),
                ('servis_tarix24ay', models.DateField(blank=True, default=False, null=True)),
                ('servis_tarix18ay', models.DateField(blank=True, default=False, null=True)),
                ('kortric1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kortric1_servis', to='mehsullar.mehsullar')),
                ('kortric2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kortric2_servis', to='mehsullar.mehsullar')),
                ('kortric3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kortric3_servis', to='mehsullar.mehsullar')),
                ('kortric4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kortric4_servis', to='mehsullar.mehsullar')),
                ('kortric5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kortric5_servis', to='mehsullar.mehsullar')),
                ('kortric6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kortric6_servis', to='mehsullar.mehsullar')),
                ('muqavile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servis', to='mehsullar.muqavile')),
            ],
        ),
        migrations.CreateModel(
            name='Emeliyyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mehsulun_sayi', models.IntegerField(default=0)),
                ('qeyd', models.TextField(default='')),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderen', to='mehsullar.anbar')),
                ('gonderilen_mehsul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_mehsul', to='mehsullar.mehsullar')),
                ('qebul_eden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qebul_eden', to='mehsullar.anbar')),
            ],
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarix', models.DateField(blank=True, default=False, null=True)),
                ('qiymet', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('muqavile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavilenin_tarixi', to='mehsullar.muqavile')),
            ],
        ),
        migrations.CreateModel(
            name='AnbarQeydler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basliq', models.CharField(max_length=100)),
                ('qeyd', models.TextField()),
                ('anbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anbar_qeyd', to='mehsullar.anbar')),
            ],
        ),
    ]
