# Generated by Django 3.2.9 on 2022-02-08 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servis',
            name='kortric1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kortric1_servis', to='mehsullar.mehsullar'),
        ),
        migrations.AlterField(
            model_name='servis',
            name='kortric2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kortric2_servis', to='mehsullar.mehsullar'),
        ),
        migrations.AlterField(
            model_name='servis',
            name='kortric3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kortric3_servis', to='mehsullar.mehsullar'),
        ),
        migrations.AlterField(
            model_name='servis',
            name='kortric4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kortric4_servis', to='mehsullar.mehsullar'),
        ),
        migrations.AlterField(
            model_name='servis',
            name='kortric5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kortric5_servis', to='mehsullar.mehsullar'),
        ),
        migrations.AlterField(
            model_name='servis',
            name='kortric6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kortric6_servis', to='mehsullar.mehsullar'),
        ),
    ]
