# Generated by Django 3.2.12 on 2022-04-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mehsullar',
            name='is_hediyye',
            field=models.BooleanField(default=False),
        ),
    ]
