# Generated by Django 3.2.9 on 2022-03-13 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuqvileHediyye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mehsul', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mehsul_hediyye', to='mehsullar.mehsullar')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.DeleteModel(
            name='Hediyye',
        ),
        migrations.RemoveField(
            model_name='muqavile',
            name='hediyye1',
        ),
        migrations.RemoveField(
            model_name='muqavile',
            name='hediyye2',
        ),
        migrations.RemoveField(
            model_name='muqavile',
            name='hediyye3',
        ),
        migrations.AddField(
            model_name='muqvilehediyye',
            name='muqavile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muqavile_hediyye', to='mehsullar.muqavile'),
        ),
    ]
