# Generated by Django 3.2.9 on 2021-12-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qeydler',
            new_name='AnbarQeydler',
        ),
    ]
