# Generated by Django 3.2.9 on 2022-02-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dates',
            new_name='OdemeTarix',
        ),
    ]
