# Generated by Django 3.2.9 on 2022-02-24 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mehsullar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anbar',
            name='ofis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofis_anbar', to='account.ofis'),
        ),
        migrations.AddField(
            model_name='anbar',
            name='shirket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirket_anbar', to='account.shirket'),
        ),
        migrations.AddField(
            model_name='emeliyyat',
            name='gonderen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gonderen', to='mehsullar.anbar'),
        ),
        migrations.AddField(
            model_name='emeliyyat',
            name='gonderilen_mehsul',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_mehsul', to='mehsullar.mehsullar'),
        ),
        migrations.AddField(
            model_name='emeliyyat',
            name='qebul_eden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qebul_eden', to='mehsullar.anbar'),
        ),
        migrations.AddField(
            model_name='muqavile',
            name='canvesser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canvesser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='muqavile',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='muqavile',
            name='hediyye1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile_hediyye1', to='mehsullar.hediyye'),
        ),
        migrations.AddField(
            model_name='muqavile',
            name='hediyye2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile_hediyye2', to='mehsullar.hediyye'),
        ),
        migrations.AddField(
            model_name='muqavile',
            name='hediyye3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile_hediyye3', to='mehsullar.hediyye'),
        ),
        migrations.AddField(
            model_name='muqavile',
            name='mehsul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mehsul_muqavile', to='mehsullar.mehsullar'),
        ),
        migrations.AddField(
            model_name='muqavile',
            name='musteri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musteri_muqavile', to='account.musteri'),
        ),
        migrations.AddField(
            model_name='muqavile',
            name='ofis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile', to='account.ofis'),
        ),
        migrations.AddField(
            model_name='muqavile',
            name='shirket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile', to='account.shirket'),
        ),
        migrations.AddField(
            model_name='muqavile',
            name='shobe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile', to='account.shobe'),
        ),
        migrations.AddField(
            model_name='muqavile',
            name='vanleader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vanleader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='odemetarix',
            name='muqavile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odeme_tarixi', to='mehsullar.muqavile'),
        ),
        migrations.AddField(
            model_name='servis',
            name='kartric1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kartric1_servis', to='mehsullar.mehsullar'),
        ),
        migrations.AddField(
            model_name='servis',
            name='kartric2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kartric2_servis', to='mehsullar.mehsullar'),
        ),
        migrations.AddField(
            model_name='servis',
            name='kartric3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kartric3_servis', to='mehsullar.mehsullar'),
        ),
        migrations.AddField(
            model_name='servis',
            name='kartric4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kartric4_servis', to='mehsullar.mehsullar'),
        ),
        migrations.AddField(
            model_name='servis',
            name='kartric5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kartric5_servis', to='mehsullar.mehsullar'),
        ),
        migrations.AddField(
            model_name='servis',
            name='kartric6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kartric6_servis', to='mehsullar.mehsullar'),
        ),
        migrations.AddField(
            model_name='servis',
            name='muqavile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servis', to='mehsullar.muqavile'),
        ),
        migrations.AddField(
            model_name='stok',
            name='anbar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mehsullar.anbar'),
        ),
        migrations.AddField(
            model_name='stok',
            name='mehsul',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mehsullar.mehsullar'),
        ),
    ]
