# Generated by Django 3.2.9 on 2022-01-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mehsullar',
            name='kateqoriya',
        ),
        migrations.DeleteModel(
            name='Kateqoriyalar',
        ),
    ]
