# Generated by Django 3.2.9 on 2022-01-15 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0002_auto_20220102_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hediyye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hediyye_adi', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='dates',
            old_name='available',
            new_name='status',
        ),
        migrations.AddField(
            model_name='emeliyyat',
            name='mehsulun_sayi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='muqavile',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='muqavile',
            name='hediyye',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile', to='mehsullar.hediyye'),
        ),
    ]
