# Generated by Django 3.2.9 on 2022-02-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0002_auto_20220208_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mehsullar',
            name='anbar',
        ),
        migrations.RemoveField(
            model_name='mehsullar',
            name='shirket',
        ),
    ]
