# Generated by Django 3.2.9 on 2022-03-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0002_auto_20220313_1514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MuqvileHediyye',
            new_name='MuqavileHediyye',
        ),
    ]
