# Generated by Django 3.2.12 on 2022-04-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0002_mehsullar_is_hediyye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muqavile',
            name='elektron_imza',
            field=models.ImageField(blank=True, null=True, upload_to='media/muqavile'),
        ),
    ]
