# Generated by Django 3.2.9 on 2022-01-04 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0002_auto_20220102_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='emeliyyat',
            name='qeyd',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mehsullar',
            name='say',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mehsullar.anbar')),
            ],
            options={
                'ordering': ('pk',),
                'unique_together': {('warehouse',)},
            },
        ),
    ]
