# Generated by Django 3.2.9 on 2022-02-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0002_auto_20220224_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muqavile',
            name='dusen',
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='odenis_uslubu',
            field=models.CharField(choices=[('KREDIT', 'KREDIT'), ('NƏĞD', 'NƏĞD')], default='NƏĞD', max_length=20),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='status',
            field=models.CharField(choices=[('BİTMİŞ', 'BİTMİŞ'), ('DAVAM_EDƏN', 'DAVAM_EDƏN'), ('LƏĞV_OLUNMUŞ', 'LƏĞV_OLUNMUŞ')], default='DAVAM_EDƏN', max_length=20),
        ),
    ]
