# Generated by Django 3.2.9 on 2022-02-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0003_auto_20220228_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='muqavile',
            name='kredit_muddeti',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
