# Generated by Django 3.2.9 on 2022-01-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0003_auto_20220104_0825'),
        ('mehsullar', '0003_auto_20220115_1731'),
    ]

    operations = [
    ]
