# Generated by Django 3.2.9 on 2022-02-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0003_auto_20220208_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='emeliyyat',
            name='emeliyyat_tarixi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
