# Generated by Django 3.2.12 on 2022-04-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0003_alter_muqavile_elektron_imza'),
    ]

    operations = [
        migrations.AddField(
            model_name='muqavile',
            name='deyisilmis_mehsul_status',
            field=models.CharField(blank=True, choices=[('DƏYİŞİLMİŞ MƏHSUL', 'DƏYİŞİLMİŞ MƏHSUL')], default=None, max_length=50, null=True),
        ),
    ]
