# Generated by Django 3.2.9 on 2022-03-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0004_mehsullar_shirket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anbarqeydler',
            name='basliq',
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='muqavile_status',
            field=models.CharField(choices=[('DAVAM EDƏN', 'DAVAM EDƏN'), ('BİTMİŞ', 'BİTMİŞ'), ('DÜŞƏN', 'DÜŞƏN')], default='DAVAM EDƏN', max_length=20),
        ),
    ]
