# Generated by Django 3.2.12 on 2022-04-18 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0004_muqavile_deyisilmis_mehsul_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servis',
            name='kartric1',
        ),
        migrations.RemoveField(
            model_name='servis',
            name='kartric2',
        ),
        migrations.RemoveField(
            model_name='servis',
            name='kartric3',
        ),
        migrations.RemoveField(
            model_name='servis',
            name='kartric4',
        ),
        migrations.RemoveField(
            model_name='servis',
            name='kartric5',
        ),
        migrations.RemoveField(
            model_name='servis',
            name='kartric6',
        ),
        migrations.RemoveField(
            model_name='servis',
            name='servis_tarix18ay',
        ),
        migrations.RemoveField(
            model_name='servis',
            name='servis_tarix24ay',
        ),
        migrations.RemoveField(
            model_name='servis',
            name='servis_tarix6ay',
        ),
        migrations.AddField(
            model_name='mehsullar',
            name='kartric_novu',
            field=models.CharField(blank=True, choices=[('KARTRIC6AY', 'KARTRIC6AY'), ('KARTRIC12AY', 'KARTRIC12AY'), ('KARTRIC18AY', 'KARTRIC18AY'), ('KARTRIC24AY', 'KARTRIC24AY')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servis',
            name='mehsullar',
            field=models.ManyToManyField(related_name='servis', to='mehsullar.Mehsullar'),
        ),
        migrations.AddField(
            model_name='servis',
            name='servis_tarix',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='servis',
            name='yerine_yetirildi',
            field=models.BooleanField(default=False),
        ),
    ]
