# Generated by Django 3.2.9 on 2022-01-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0004_merge_0003_auto_20220104_0825_0003_auto_20220115_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hediyye2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hediyye_adi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hediyye3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hediyye_adi', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='muqavile',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
