# Generated by Django 3.2.9 on 2022-02-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0004_emeliyyat_emeliyyat_tarixi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emeliyyat',
            name='emeliyyat_tarixi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
