# Generated by Django 3.2.9 on 2022-02-28 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0004_muqavile_kredit_muddeti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muqavile',
            name='hediyye1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile_hediyye1', to='mehsullar.mehsullar'),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='hediyye2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile_hediyye2', to='mehsullar.mehsullar'),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='hediyye3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile_hediyye3', to='mehsullar.mehsullar'),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='ilkin_odenis_status',
            field=models.CharField(choices=[('BİTMİŞ', 'BİTMİŞ'), ('DAVAM EDƏN', 'DAVAM EDƏN'), ('LƏĞV OLUNMUŞ', 'LƏĞV OLUNMUŞ')], default='DAVAM EDƏN', max_length=20),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='status',
            field=models.CharField(choices=[('BİTMİŞ', 'BİTMİŞ'), ('DAVAM EDƏN', 'DAVAM EDƏN'), ('LƏĞV OLUNMUŞ', 'LƏĞV OLUNMUŞ')], default='DAVAM EDƏN', max_length=20),
        ),
    ]
