# Generated by Django 3.2.9 on 2022-01-17 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0005_auto_20220117_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='muqavile',
            name='hediyye2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile', to='mehsullar.hediyye2'),
        ),
        migrations.AddField(
            model_name='muqavile',
            name='hediyye3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile', to='mehsullar.hediyye3'),
        ),
    ]
