# Generated by Django 3.2.9 on 2022-03-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0005_auto_20220314_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='odemetarix',
            name='borcu_bagla_status',
            field=models.CharField(blank=True, choices=[('BORCU BAĞLA', 'BORCU BAĞLA')], default=None, max_length=30, null=True),
        ),
    ]
