# Generated by Django 3.2.12 on 2022-04-19 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0005_auto_20220418_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServisOdeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servis_qiymeti', models.FloatField(blank=True, default=0)),
                ('endrim', models.FloatField(blank=True, default=0)),
                ('odenilecek_mebleg', models.FloatField(blank=True, default=0)),
                ('qeyd', models.TextField()),
                ('odendi', models.BooleanField(default=False)),
                ('servis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servis_odeme', to='mehsullar.servis')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
