# Generated by Django 3.2.9 on 2022-02-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0005_auto_20220228_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muqavile',
            old_name='status',
            new_name='muqavile_status',
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='ilkin_odenis_status',
            field=models.CharField(choices=[('BİTMİŞ', 'BİTMİŞ'), ('DAVAM EDƏN', 'DAVAM EDƏN'), ('LƏĞV OLUNMUŞ', 'LƏĞV OLUNMUŞ')], default='YOXDUR', max_length=20),
        ),
    ]
