# Generated by Django 3.2.9 on 2022-03-15 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('mehsullar', '0006_odemetarix_borcu_bagla_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anbar',
            name='ofis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofis_anbar', to='company.ofis'),
        ),
        migrations.AlterField(
            model_name='anbar',
            name='shirket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirket_anbar', to='company.shirket'),
        ),
        migrations.AlterField(
            model_name='mehsullar',
            name='shirket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirket_mehsul', to='company.shirket'),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='ofis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile', to='company.ofis'),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='shirket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile', to='company.shirket'),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='shobe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile', to='company.shobe'),
        ),
    ]
