# Generated by Django 3.2.9 on 2022-02-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0006_auto_20220228_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muqavile',
            name='ilkin_odenis_status',
            field=models.CharField(choices=[('BİTMİŞ', 'BİTMİŞ'), ('DAVAM EDƏN', 'DAVAM EDƏN'), ('YOXDUR', 'YOXDUR')], default='YOXDUR', max_length=20),
        ),
    ]
