# Generated by Django 3.2.9 on 2022-02-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0006_alter_emeliyyat_qeyd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servis',
            old_name='kortric1',
            new_name='kartric1',
        ),
        migrations.RenameField(
            model_name='servis',
            old_name='kortric2',
            new_name='kartric2',
        ),
        migrations.RenameField(
            model_name='servis',
            old_name='kortric3',
            new_name='kartric3',
        ),
        migrations.RenameField(
            model_name='servis',
            old_name='kortric4',
            new_name='kartric4',
        ),
        migrations.RenameField(
            model_name='servis',
            old_name='kortric5',
            new_name='kartric5',
        ),
        migrations.RenameField(
            model_name='servis',
            old_name='kortric6',
            new_name='kartric6',
        ),
    ]
