# Generated by Django 3.2.12 on 2022-04-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0006_servisodeme'),
    ]

    operations = [
        migrations.AddField(
            model_name='servis',
            name='servis_qiymeti',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='servisodeme',
            name='qeyd',
            field=models.TextField(blank=True),
        ),
    ]
