# Generated by Django 3.2.9 on 2022-01-20 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_last_login'),
        ('mehsullar', '0007_auto_20220118_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='muqavile',
            name='shobe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile', to='account.shobe'),
        ),
    ]
