# Generated by Django 3.2.9 on 2022-02-10 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0007_auto_20220210_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servis',
            name='kartric1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kartric1_servis', to='mehsullar.mehsullar'),
        ),
        migrations.AlterField(
            model_name='servis',
            name='kartric2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kartric2_servis', to='mehsullar.mehsullar'),
        ),
        migrations.AlterField(
            model_name='servis',
            name='kartric3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kartric3_servis', to='mehsullar.mehsullar'),
        ),
        migrations.AlterField(
            model_name='servis',
            name='kartric4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kartric4_servis', to='mehsullar.mehsullar'),
        ),
        migrations.AlterField(
            model_name='servis',
            name='kartric5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kartric5_servis', to='mehsullar.mehsullar'),
        ),
        migrations.AlterField(
            model_name='servis',
            name='kartric6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kartric6_servis', to='mehsullar.mehsullar'),
        ),
    ]
