# Generated by Django 3.2.9 on 2022-03-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0007_auto_20220315_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='muqavile',
            name='kompensasiya_medaxil',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='muqavile',
            name='kompensasiya_mexaric',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
