# Generated by Django 3.2.9 on 2022-02-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0007_alter_muqavile_ilkin_odenis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='muqavile',
            name='negd_odenis_1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='muqavile',
            name='negd_odenis_1_tarix',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muqavile',
            name='negd_odenis_2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='muqavile',
            name='negd_odenis_2_tarix',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='odenis_uslubu',
            field=models.CharField(choices=[('KREDIT', 'KREDIT'), ('NƏĞD', 'NƏĞD'), ('İKİ DƏFƏYƏ NƏĞD', 'İKİ DƏFƏYƏ NƏĞD')], default='NƏĞD', max_length=20),
        ),
    ]
