# Generated by Django 3.2.9 on 2022-02-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0008_auto_20220228_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muqavile',
            name='ilkin_odenis',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='ilkin_odenis_qaliq',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='verilecek_ilkin_odenis',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
