# Generated by Django 3.2.9 on 2022-01-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0008_muqavile_shobe'),
    ]

    operations = [
        migrations.AddField(
            model_name='muqavile',
            name='odenis_uslubu',
            field=models.BooleanField(default=True),
        ),
    ]
