# Generated by Django 3.2.12 on 2022-04-19 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0009_servis_servis_qiymeti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servis',
            name='mehsullar',
            field=models.ManyToManyField(related_name='servis_mehsul', to='mehsullar.Mehsullar'),
        ),
        migrations.AlterField(
            model_name='servis',
            name='muqavile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servis_muqavile', to='mehsullar.muqavile'),
        ),
    ]
