# Generated by Django 3.2.9 on 2022-03-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0009_auto_20220316_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muqavile',
            name='kompensasiya_medaxil',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='kompensasiya_mexaric',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
