# Generated by Django 3.2.9 on 2022-01-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0009_muqavile_odenis_uslubu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dates',
            name='ilkin_odenis',
        ),
        migrations.AddField(
            model_name='muqavile',
            name='ilkin_odenis',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muqavile',
            name='ilkin_odenis_tarixi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
