# Generated by Django 3.2.9 on 2022-08-10 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0009_alter_servis_kartric1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servis',
            name='kartric1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kartric1_servis', to='mehsullar.mehsullar'),
        ),
    ]
