# Generated by Django 3.2.9 on 2022-03-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0010_alter_odemetarix_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odemetarix',
            name='status',
            field=models.CharField(choices=[('ÖDƏNƏN', 'ÖDƏNƏN'), ('ÖDƏNMƏYƏN', 'ÖDƏNMƏYƏN'), ('BURAXILMIŞ AY', 'BURAXILMIŞ AY'), ('NATAMAM AY', 'NATAMAM AY')], default='ÖDƏNMƏYƏN', max_length=20),
        ),
    ]
