# Generated by Django 3.2.12 on 2022-04-19 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0010_auto_20220419_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='servisodeme',
            name='odeme_tarix',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='servis',
            name='servis_tarix',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
