# Generated by Django 3.2.9 on 2022-03-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0010_auto_20220316_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='odemetarix',
            name='sertli_odeme_status',
            field=models.CharField(blank=True, choices=[('BURAXILMIŞ AY', 'BURAXILMIŞ AY'), ('NATAMAM AY', 'NATAMAM AY'), ('RAZILAŞDIRILMIŞ AZ ÖDƏMƏ', 'RAZILAŞDIRILMIŞ AZ ÖDƏMƏ'), ('YENİ QRAFİK', 'YENİ QRAFİK'), ('ARTIQ ÖDƏMƏ', 'ARTIQ ÖDƏMƏ'), ('SON AYIN BÖLÜNMƏSİ', 'SON AYIN BÖLÜNMƏSİ')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='odemetarix',
            name='odenme_status',
            field=models.CharField(choices=[('ÖDƏNMƏYƏN', 'ÖDƏNMƏYƏN'), ('ÖDƏNƏN', 'ÖDƏNƏN')], default='ÖDƏNMƏYƏN', max_length=30),
        ),
    ]
