# Generated by Django 3.2.9 on 2022-01-21 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mehsullar', '0010_auto_20220120_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='muqavile',
            name='vanleader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vanleader', to=settings.AUTH_USER_MODEL),
        ),
    ]
