# Generated by Django 3.2.12 on 2022-04-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0011_auto_20220419_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='servisodeme',
            name='ilkin_odenis',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
