# Generated by Django 3.2.9 on 2022-03-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0011_auto_20220319_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='muqavile',
            name='yeni_qrafik_status',
            field=models.CharField(blank=True, choices=[('YENİ QRAFİK', 'YENİ QRAFİK')], default=None, max_length=50, null=True),
        ),
    ]
