# Generated by Django 3.2.9 on 2022-01-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0011_muqavile_vanleader'),
    ]

    operations = [
        migrations.AddField(
            model_name='muqavile',
            name='dusen',
            field=models.BooleanField(default=False),
        ),
    ]
