# Generated by Django 3.2.9 on 2022-03-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0012_muqavile_yeni_qrafik_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='muqavile',
            name='yeni_qrafik_mebleg',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='odemetarix',
            name='sertli_odeme_status',
            field=models.CharField(blank=True, choices=[('BURAXILMIŞ AY', 'BURAXILMIŞ AY'), ('NATAMAM AY', 'NATAMAM AY'), ('RAZILAŞDIRILMIŞ AZ ÖDƏMƏ', 'RAZILAŞDIRILMIŞ AZ ÖDƏMƏ'), ('ARTIQ ÖDƏMƏ', 'ARTIQ ÖDƏMƏ'), ('SON AYIN BÖLÜNMƏSİ', 'SON AYIN BÖLÜNMƏSİ')], default=None, max_length=50, null=True),
        ),
    ]
