# Generated by Django 3.2.9 on 2022-03-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0012_alter_odemetarix_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odemetarix',
            old_name='status',
            new_name='odenme_status',
        ),
    ]
