# Generated by Django 3.2.9 on 2022-03-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0013_rename_status_odemetarix_odenme_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='odemetarix',
            name='sifira_gore_odeme_status',
            field=models.CharField(blank=True, choices=[('SIFIR NÖVBƏTİ AY', 'SIFIR NÖVBƏTİ AY'), ('SIFIR SONUNCU AY', 'SIFIR SONUNCU AY'), ('SIFIR DİGƏR AYLAR', 'SIFIR DİGƏR AYLAR')], default=None, max_length=20, null=True),
        ),
    ]
