# Generated by Django 3.2.12 on 2022-04-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0013_auto_20220419_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='servis',
            name='kredit_muddeti',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
