# Generated by Django 3.2.9 on 2022-01-24 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0013_alter_user_vezife'),
        ('mehsullar', '0013_alter_muqavile_elektron_imza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muqavile',
            name='canvesser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canvesser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='dusen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='mehsul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mehsul_muqavile', to='mehsullar.mehsullar'),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='muqavile_tarixi',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='musteri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musteri_muqavile', to='account.musteri'),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='shirket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile', to='account.shirket'),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='shobe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile', to='account.shobe'),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='vanleader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vanleader', to=settings.AUTH_USER_MODEL),
        ),
    ]
