# Generated by Django 3.2.12 on 2022-04-20 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0014_servis_kredit_muddeti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muqavile',
            name='muqavile_tarixi',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
