# Generated by Django 3.2.9 on 2022-03-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0014_odemetarix_sifira_gore_odeme_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='odemetarix',
            name='natamama_gore_odeme_status',
            field=models.CharField(blank=True, choices=[('NATAMAM NÖVBƏTİ AY', 'NATAMAM NÖVBƏTİ AY'), ('NATAMAM SONUNCU AY', 'NATAMAM SONUNCU AY'), ('NATAMAM DİGƏR AYLAR', 'NATAMAM DİGƏR AYLAR')], default=None, max_length=20, null=True),
        ),
    ]
