# Generated by Django 3.2.9 on 2022-01-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0014_auto_20220124_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muqavile',
            name='dusen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
