# Generated by Django 3.2.9 on 2022-03-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0015_odemetarix_natamama_gore_odeme_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odemetarix',
            name='odenme_status',
            field=models.CharField(choices=[('ÖDƏNMƏYƏN', 'ÖDƏNMƏYƏN'), ('ÖDƏNƏN', 'ÖDƏNƏN'), ('BURAXILMIŞ AY', 'BURAXILMIŞ AY'), ('NATAMAM AY', 'NATAMAM AY'), ('RAZILAŞDIRILMIŞ AZ ÖDƏMƏ', 'RAZILAŞDIRILMIŞ AZ ÖDƏMƏ')], default='ÖDƏNMƏYƏN', max_length=30),
        ),
    ]
