# Generated by Django 3.2.9 on 2022-01-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0015_auto_20220124_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muqavile',
            name='hediyye3',
        ),
    ]
