# Generated by Django 3.2.9 on 2022-01-24 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0016_remove_muqavile_hediyye3'),
    ]

    operations = [
        migrations.AddField(
            model_name='muqavile',
            name='hediyye3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muqavile_hediyye3', to='mehsullar.hediyye'),
        ),
    ]
