# Generated by Django 3.2.9 on 2022-03-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0017_alter_odemetarix_odenme_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odemetarix',
            name='odenme_status',
            field=models.CharField(choices=[('ÖDƏNMƏYƏN', 'ÖDƏNMƏYƏN'), ('ÖDƏNƏN', 'ÖDƏNƏN'), ('BURAXILMIŞ AY', 'BURAXILMIŞ AY'), ('NATAMAM AY', 'NATAMAM AY'), ('RAZILAŞDIRILMIŞ AZ ÖDƏMƏ', 'RAZILAŞDIRILMIŞ AZ ÖDƏMƏ'), ('YENİ QRAFİK', 'YENİ QRAFİK'), ('ARTIQ ÖDƏMƏ', 'ARTIQ ÖDƏMƏ')], default='ÖDƏNMƏYƏN', max_length=30),
        ),
    ]
