# Generated by Django 3.2.9 on 2022-02-06 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0017_muqavile_hediyye3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servis_tarix6ay', models.DateField(default=False)),
                ('servis_tarix24ay', models.DateField(default=False)),
                ('servis_tarix18ay', models.DateField(default=False)),
                ('kortric1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kortric1_servis', to='mehsullar.mehsullar')),
                ('kortric2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kortric2_servis', to='mehsullar.mehsullar')),
                ('kortric3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kortric3_servis', to='mehsullar.mehsullar')),
                ('kortric4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kortric4_servis', to='mehsullar.mehsullar')),
                ('kortric5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kortric5_servis', to='mehsullar.mehsullar')),
                ('kortric6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kortric6_servis', to='mehsullar.mehsullar')),
                ('muqavile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servis', to='mehsullar.muqavile')),
            ],
        ),
    ]
