# Generated by Django 3.2.9 on 2022-03-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0018_alter_odemetarix_odenme_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odemetarix',
            old_name='sifira_gore_odeme_status',
            new_name='buraxilmis_ay_alt_status',
        ),
        migrations.RenameField(
            model_name='odemetarix',
            old_name='natamama_gore_odeme_status',
            new_name='natamam_ay_alt_status',
        ),
        migrations.AddField(
            model_name='odemetarix',
            name='artiq_odeme_alt_status',
            field=models.CharField(blank=True, choices=[('ARTIQ_BİR_AY', 'ARTIQ_BİR_AY'), ('ARTIQ_BÜTÜN_AYLAR', 'ARTIQ_BÜTÜN_AYLAR')], default=None, max_length=20, null=True),
        ),
    ]
