# Generated by Django 3.2.9 on 2022-02-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0018_servis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servis',
            name='servis_tarix18ay',
            field=models.DateField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='servis',
            name='servis_tarix24ay',
            field=models.DateField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='servis',
            name='servis_tarix6ay',
            field=models.DateField(blank=True, default=False, null=True),
        ),
    ]
