# Generated by Django 3.2.9 on 2022-03-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0019_auto_20220307_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muqavile',
            name='ilkin_odenis_status',
            field=models.CharField(choices=[('YOXDUR', 'YOXDUR'), ('BİTMİŞ', 'BİTMİŞ'), ('DAVAM EDƏN', 'DAVAM EDƏN')], default='YOXDUR', max_length=20),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='muqavile_status',
            field=models.CharField(choices=[('DAVAM EDƏN', 'DAVAM EDƏN'), ('BİTMİŞ', 'BİTMİŞ'), ('LƏĞV OLUNMUŞ', 'LƏĞV OLUNMUŞ')], default='DAVAM EDƏN', max_length=20),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='odenis_uslubu',
            field=models.CharField(choices=[('NƏĞD', 'NƏĞD'), ('KREDIT', 'KREDIT'), ('İKİ DƏFƏYƏ NƏĞD', 'İKİ DƏFƏYƏ NƏĞD')], default='NƏĞD', max_length=20),
        ),
        migrations.AlterField(
            model_name='odemetarix',
            name='odenme_status',
            field=models.CharField(choices=[('ÖDƏNMƏYƏN', 'ÖDƏNMƏYƏN'), ('ÖDƏNƏN', 'ÖDƏNƏN'), ('BURAXILMIŞ AY', 'BURAXILMIŞ AY'), ('NATAMAM AY', 'NATAMAM AY'), ('RAZILAŞDIRILMIŞ AZ ÖDƏMƏ', 'RAZILAŞDIRILMIŞ AZ ÖDƏMƏ'), ('YENİ QRAFİK', 'YENİ QRAFİK'), ('ARTIQ ÖDƏMƏ', 'ARTIQ ÖDƏMƏ'), ('GECİKDİRMƏ', 'GECİKDİRMƏ'), ('SON AYIN BÖLÜNMƏSİ', 'SON AYIN BÖLÜNMƏSİ')], default='ÖDƏNMƏYƏN', max_length=30),
        ),
    ]
