# Generated by Django 3.2.9 on 2022-02-07 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0020_auto_20220207_1449'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Stok',
        ),
    ]
