# Generated by Django 3.2.9 on 2022-02-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0021_rename_stock_stok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mehsullar',
            name='say',
        ),
    ]
