# Generated by Django 3.2.9 on 2022-03-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0021_alter_odemetarix_odenme_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='odemetarix',
            name='gecikdirme_status',
            field=models.CharField(choices=[('GECİKDİRMƏ', 'GECİKDİRMƏ')], default='GECİKDİRMƏ', max_length=30),
        ),
    ]
