# Generated by Django 3.2.9 on 2022-03-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0022_odemetarix_gecikdirme_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muqavile',
            name='ilkin_odenis',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='ilkin_odenis_qaliq',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='odenis_uslubu',
            field=models.CharField(choices=[('NƏĞD', 'NƏĞD'), ('KREDİT', 'KREDİT'), ('İKİ DƏFƏYƏ NƏĞD', 'İKİ DƏFƏYƏ NƏĞD')], default='NƏĞD', max_length=20),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='verilecek_ilkin_odenis',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='odemetarix',
            name='gecikdirme_status',
            field=models.CharField(blank=True, choices=[('GECİKDİRMƏ', 'GECİKDİRMƏ')], default=None, max_length=30, null=True),
        ),
    ]
