# Generated by Django 3.2.9 on 2022-03-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0023_auto_20220309_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muqavile',
            name='kredit_muddeti',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
