# Generated by Django 3.2.9 on 2022-03-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0024_alter_muqavile_kredit_muddeti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odemetarix',
            name='qiymet',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
