# Generated by Django 3.2.9 on 2022-03-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0025_alter_odemetarix_qiymet'),
    ]

    operations = [
        migrations.AddField(
            model_name='muqavile',
            name='mehsul_sayi',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
