# Generated by Django 3.2.9 on 2022-03-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0029_alter_odemetarix_qiymet'),
    ]

    operations = [
        migrations.AddField(
            model_name='muqavile',
            name='muqavile_umumi_mebleg',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
