# Generated by Django 3.2.9 on 2022-03-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0030_muqavile_muqavile_umumi_mebleg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muqavile',
            name='ilkin_odenis',
        ),
    ]
