# Generated by Django 3.2.9 on 2022-03-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0031_remove_muqavile_ilkin_odenis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muqavile',
            old_name='verilecek_ilkin_odenis',
            new_name='ilkin_odenis',
        ),
    ]
