# Generated by Django 3.2.9 on 2022-03-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0032_rename_verilecek_ilkin_odenis_muqavile_ilkin_odenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muqavile',
            name='muqavile_status',
            field=models.CharField(choices=[('DAVAM EDƏN', 'DAVAM EDƏN'), ('BİTMİŞ', 'BİTMİŞ'), ('LƏĞV OLUNMUŞ', 'LƏĞV OLUNMUŞ'), ('GECİKDİRMƏ', 'GECİKDİRMƏ')], default='DAVAM EDƏN', max_length=20),
        ),
    ]
