# Generated by Django 3.2.9 on 2022-03-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0033_alter_muqavile_muqavile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='muqavile',
            name='negd_odenis_gecikdirme',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='muqavile',
            name='muqavile_status',
            field=models.CharField(choices=[('DAVAM EDƏN', 'DAVAM EDƏN'), ('BİTMİŞ', 'BİTMİŞ'), ('LƏĞV OLUNMUŞ', 'LƏĞV OLUNMUŞ')], default='DAVAM EDƏN', max_length=20),
        ),
    ]
