# Generated by Django 3.2.9 on 2022-03-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0034_auto_20220312_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='muqavile',
            name='negd_odenis_1_status',
            field=models.CharField(choices=[('YOXDUR', 'YOXDUR'), ('BİTMİŞ', 'BİTMİŞ'), ('DAVAM EDƏN', 'DAVAM EDƏN')], default='YOXDUR', max_length=20),
        ),
        migrations.AddField(
            model_name='muqavile',
            name='negd_odenis_2_status',
            field=models.CharField(choices=[('YOXDUR', 'YOXDUR'), ('BİTMİŞ', 'BİTMİŞ'), ('DAVAM EDƏN', 'DAVAM EDƏN')], default='YOXDUR', max_length=20),
        ),
        migrations.AddField(
            model_name='muqavile',
            name='qaliq_ilkin_odenis_status',
            field=models.CharField(choices=[('YOXDUR', 'YOXDUR'), ('BİTMİŞ', 'BİTMİŞ'), ('DAVAM EDƏN', 'DAVAM EDƏN')], default='YOXDUR', max_length=20),
        ),
    ]
