# Generated by Django 3.2.9 on 2022-03-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0035_auto_20220312_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muqavile',
            name='negd_odenis_gecikdirme',
        ),
    ]
