# Generated by Django 3.2.9 on 2022-03-15 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingKassaMexaric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mebleg', models.FloatField(default=0, null=True)),
                ('qebzin_resmi', models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d/')),
                ('qeyd', models.TextField(blank=True, null=True)),
                ('holding_kassa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holding_kassa_mexaric', to='company.holdingkassa')),
            ],
        ),
    ]
