# Generated by Django 3.2.12 on 2022-05-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_holdingdenshirketleretransfer_holdingkassamedaxil_holdingkassamexaric_ofisdenshirketetransfer_ofiska'),
    ]

    operations = [
        migrations.AddField(
            model_name='komanda',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
