# Generated by Django 3.2.9 on 2022-03-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20220315_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdingkassamedaxil',
            name='medaxil_tarixi',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='holdingkassamexaric',
            name='mexaric_tarixi',
            field=models.DateField(default=None),
        ),
    ]
