# Generated by Django 3.2.12 on 2022-04-18 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0004_muqavile_deyisilmis_mehsul_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_komanda_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServisKreditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kreditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servis_kreditor', to=settings.AUTH_USER_MODEL)),
                ('servis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kreditor', to='mehsullar.servis')),
            ],
        ),
        migrations.CreateModel(
            name='MuqavileKreditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kreditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muqavile_kreditor', to=settings.AUTH_USER_MODEL)),
                ('muqavile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kreditor', to='mehsullar.muqavile')),
            ],
        ),
    ]
