# Generated by Django 3.2.12 on 2022-04-01 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_muqavilekreditor_serviskreditor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServisKreditor',
        ),
    ]
