# Generated by Django 3.2.9 on 2022-03-16 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0006_auto_20220315_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holdingkassamedaxil',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='holdingkassamexaric',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='ofiskassamedaxil',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='ofiskassamexaric',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='shirketkassamedaxil',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='shirketkassamexaric',
            options={'ordering': ('pk',)},
        ),
        migrations.AddField(
            model_name='ofiskassamedaxil',
            name='medaxil_eden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_medaxil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ofiskassamexaric',
            name='mexaric_eden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_mexaric', to=settings.AUTH_USER_MODEL),
        ),
    ]
