# Generated by Django 3.2.9 on 2022-03-16 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0007_auto_20220316_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdingkassamedaxil',
            name='medaxil_eden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_holding_medaxil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holdingkassamexaric',
            name='mexaric_eden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_holding_mexaric', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shirketkassamedaxil',
            name='medaxil_eden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_shirket_medaxil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shirketkassamexaric',
            name='mexaric_eden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_shirket_mexaric', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ofiskassamedaxil',
            name='medaxil_eden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ofis_medaxil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ofiskassamexaric',
            name='mexaric_eden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ofis_mexaric', to=settings.AUTH_USER_MODEL),
        ),
    ]
