# Generated by Django 3.2.9 on 2022-03-16 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0008_auto_20220316_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdingdenshirketleretransfer',
            name='transfer_eden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_holding_shirket_transfer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ofisdenshirketetransfer',
            name='transfer_eden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ofis_shirket_transfer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shirketdenholdingetransfer',
            name='transfer_eden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_shirket_holding_transfer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shirketdenofisleretransfer',
            name='transfer_eden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_shirket_ofis_transfer', to=settings.AUTH_USER_MODEL),
        ),
    ]
